### ISSUE TITLE
Test VM: VirtualBox guest additions fail to build (missing kernel headers)

### ISSUE THREAD

**Issue by MMatten** [dbfit/dbfit#419]
The test VM is failing to come up on `vagrant up` as it looks like the kernel headers are now no longer on the CentOS 6.6 image (and the same issue occurs when trying to use CentOS 7).

Also, the headers for the CentOS 6.6 image's kernel version on the VM don't seem to be available to the default yum repositories. 

The work-around is to use a version of VirtualBox that matches the guest additions that are already on the CentOS image (4.3.26 works) or to manually install the headers. E.g. with

` yum install ftp://mirror.switch.ch/pool/4/mirror/scientificlinux/6.6/x86_64/os/Packages/kernel-devel-2.6.32-504.el6.x86_64.rpm`

and then `vagrant reload`.

I'm not sure this is possible to fix in the DbFit VM provisioning. I.e. is it possible to inject this `yum` command before the guest additions get built?

I'm not sure this is desirable either as it's more stuff to have to maintain.

Any views?

**Comment by javornikolov** [comment]
> Also, the headers for the CentOS 6.6 image's kernel version on the VM don't seem to be available to the default yum repositories.

This sounds strange... There should be a packages with kernel headers. I can see kernel-devel and/or kernel-headers e.g. here: http://mirror.centos.org/centos/6/updates/x86_64/Packages/

**Comment by javornikolov** [comment]
What happens if kernel version is not explicitly specified: `yum install kernel-devel`

I can see in [CentOS versioning notes](https://wiki.centos.org/FAQ/General#head-dcca41e9a3d5ac4c6d900a991990fd11930867d6) that old releases are being deprecated. There is `readme` file only in the folders for the obsolete releases: http://mirror.centos.org/centos/6.6/. Maybe the way to go is to install the latest version of both the kernel and headers - they should be available in the official yum repos.

If we come up with a working solution, perhaps we make a fix for [`vagrant-vbguest / redhat.rb`](https://github.com/dotless-de/vagrant-vbguest/blob/master/lib/vagrant-vbguest/installers/redhat.rb)

**Comment by javornikolov** [comment]
There is a CentOS 7.1 mirror at http://www.vagrantbox.es/ perhaps we can give it a try too (7.1 seems to be the latest 7.x release).

**Comment by MMatten** [comment]
`uname -r` shows the kernel as `2.6.32-504.el6.x86_64`. There are no source installed at `/usr/src/kernels` - the directory is empty.

I think there's a linker error whilst building the guest additions during
`  ld -r -m elf_x86_64 -T /usr/src/kernels/2.6.32-504.el6.x86_64/scripts/module-common.lds --build-id -o /tmp/vbox.0/vboxvideo.ko /tm
p/vbox.0/vboxvideo.o /tmp/vbox.0/vboxvideo.mod.o`.

Running `yum install kernel-devel` seems to pull down the latest on the package repo (in this case it's pulled `kernel-devel.x86_64 0:2.6.32-573.3.1.el6`) not the version to match the kernel binaries.

**Comment by MMatten** [comment]
I'll try that 7.1 image and see if that helps.

**Comment by MMatten** [comment]
The box `Opscode centos-7.1` is incorrectly marked as a VirtualBox image but vagrant reports it as `vmware_desktop` and errors :confused: 

The other Centos 7.1 box on here (`CentOS 7 x64 (Minimal, Shrinked, Guest Additions 4.3.26) (Monthly updates)`) works better but Postgres provisioning fails:

==> default:     ================================================================================
==> default:     Error executing action `restart` on resource 'service[postgresql]'
==> default:     ================================================================================
==> default:
==> default:     Mixlib::ShellOut::ShellCommandFailed
==> default:     ------------------------------------
==> default:     Expected process to exit with [0], but received '1'
==> default:     ---- Begin output of /bin/systemctl restart postgresql-9.3 ----
==> default:     STDOUT:
==> default:     STDERR: Job for postgresql-9.3.service failed. See 'systemctl status postgresql-9.3.service' and 'journalctl -xn' f
or details.
==> default:     ---- End output of /bin/systemctl restart postgresql-9.3 ----
==> default:     Ran /bin/systemctl restart postgresql-9.3 returned 1

Attempting to get more info on the error didn't really help: -

`
[vagrant@dbfitvm ~]$ systemctl status postgresql-9.3.service
postgresql-9.3.service - PostgreSQL 9.3 database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql-9.3.service; disabled)
   Active: failed (Result: exit-code) since Sat 2015-08-15 20:54:53 UTC; 6min ago
  Process: 9784 ExecStartPre=/usr/pgsql-9.3/bin/postgresql93-check-db-dir ${PGDATA} (code=exited, status=1/FAILURE)```

I'm not sure where to dig next.

**Comment by javornikolov** [comment]
I forked `postgresql` cookbook so that we can experiment with it (I added support for postgresql 9.4 there).
Can you try how it works with the version in `test-vm-update-postgresql-to-9.4` branch? (It's an attempt to bump up postgresql to 9.4).

**Comment by MMatten** [comment]
Great. I'll have a go with that and report back.

**Comment by MMatten** [comment]
The same error appears: -


==> default:     ================================================================================
==> default:     Error executing action `restart` on resource 'service[postgresql]'
==> default:     ================================================================================
==> default:
==> default:     Mixlib::ShellOut::ShellCommandFailed
==> default:     ------------------------------------
==> default:     Expected process to exit with [0], but received '1'
==> default:     ---- Begin output of /bin/systemctl restart postgresql-9.4 ----
==> default:     STDOUT:
==> default:     STDERR: Job for postgresql-9.4.service failed. See 'systemctl status postgresql-9.4.service' and 'journalctl -xn' f
or details.
==> default:     ---- End output of /bin/systemctl restart postgresql-9.4 ----
==> default:     Ran /bin/systemctl restart postgresql-9.4 returned 1


Anything else I can try tweaking?

**Comment by MMatten** [comment]
Hmmm....let me try that again with a clean checkout (clearing out the existing `cookbooks` dir).

**Comment by MMatten** [comment]
Nope. That didn't help either.

Stack trace:

Generated at 2015-08-15 22:52:03 +0000
Chef::Exceptions::MultipleFailures: Chef::Exceptions::MultipleFailures
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout.rb:276:in `error!'
/opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:56:in `shell_out!'
/opt/chef/embedded/apps/chef/lib/chef/provider/execute.rb:61:in `block in action_run'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:175:in `converge_by'
/opt/chef/embedded/apps/chef/lib/chef/provider/execute.rb:60:in `action_run'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:140:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:584:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:654:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:688:in `converge_and_save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:269:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:269:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:247:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
/bin/chef-solo:55:in `load'
/bin/chef-solo:55:in `<main>'

I can see an interesting message though when I look at the status of the service:

[vagrant@dbfitvm ~]$ sudo systemctl -l status postgresql-9.4.service
postgresql-9.4.service - PostgreSQL 9.4 database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql-9.4.service; disabled)
   Active: failed (Result: exit-code) since Sat 2015-08-15 22:52:03 UTC; 3min 38s ago
  Process: 9577 ExecStartPre=/usr/pgsql-9.4/bin/postgresql94-check-db-dir ${PGDATA} (code=exited, status=1/FAILURE)

Aug 15 22:52:03 dbfitvm systemd[1]: Starting PostgreSQL 9.4 database server...
Aug 15 22:52:03 dbfitvm postgresql94-check-db-dir[9577]: "/var/lib/pgsql/9.4/data/" is missing or empty.
Aug 15 22:52:03 dbfitvm postgresql94-check-db-dir[9577]: Use "/usr/pgsql-9.4/bin/postgresql94-setup initdb" to initialize the databa
se cluster.
Aug 15 22:52:03 dbfitvm postgresql94-check-db-dir[9577]: See %{_pkgdocdir}/README.rpm-dist for more information.
Aug 15 22:52:03 dbfitvm systemd[1]: postgresql-9.4.service: control process exited, code=exited status=1
Aug 15 22:52:03 dbfitvm systemd[1]: Failed to start PostgreSQL 9.4 database server.
Aug 15 22:52:03 dbfitvm systemd[1]: Unit postgresql-9.4.service entered failed state.

I.e. the lines:

Aug 15 22:52:03 dbfitvm postgresql94-check-db-dir[9577]: "/var/lib/pgsql/9.4/data/" is missing or empty.
Aug 15 22:52:03 dbfitvm postgresql94-check-db-dir[9577]: Use "/usr/pgsql-9.4/bin/postgresql94-setup initdb" to initialize the database cluster.

I ran:

[vagrant@dbfitvm ~]$ sudo /usr/pgsql-9.4/bin/postgresql94-setup initdb
Initializing database ... OK

Finally `vagrant provision` the runs past the previous failure point. I ran out of disk space though when the DB2 installer was running. May be we can extend the available disk space on the image.

**Comment by MMatten** [comment]
From a little googling it doesn't look like it's easy to resize drives in vagrant. 

There are boxes at https://atlas.hashicorp.com/puppetlabs that might be useful but I can only see CentOS 7 not 7.1.

**Comment by javornikolov** [comment]
Regarding postgresql: I found a pending PR hw-cookbooks/postgresql#269 which I merged into our fork. I hope it would solve the mentioned issue (should invoke `initdb` itself).

In general it's possible to extend the file system, at least manually. Is the problematic file system on LVM or it's plan disk (/dev/sd*)? Is there a need to expand the disk(s) or just file system? (For the former there are VirtualBox tools; for the latter - there is resize2fs).

For the sake of trying at least something - I guess it's also possible initially to just skip DB2 provisioning.

**Comment by MMatten** [comment]
I've just noticed the `chef/centos-7.1` box on `https://atlas.hashicorp.com/chef`. This has the correct kernel headers installed so this could be the best option.

However, I still get the same Postgresql error. 

Do I need to do something with `Cheffile.lock` to get your recipe changes?

**Comment by javornikolov** [comment]
> Do I need to do something with Cheffile.lock to get your recipe changes?

Yes, please remove your `Cheffile.lock`, `cookbooks`, `tmp`.

**Comment by MMatten** [comment]
This new image is short of drive space too.

But I've managed to run the provisioning without Oracle and DB2.

...but when I ran the Postgres integration tests they fail on one Flow Mode test: `DbFit.AcceptanceTests.JavaTests.PostgresTests.FlowMode.CoreTests.CommonSuite.ParameterS`.
Each produce an exception but I can't get to the detailed message (there are no other files in `/var/dbfit/tmp` from where I can get a more detailed message) as the port forwarding (host 8085 to guest 8085) doesn't now seem to work.

I'll try to find some time this evening to try the CentOS 7.0 box at `https://atlas.hashicorp.com/puppetlabs`.

(This stuff does seem pretty fragile. Is it worth perhaps creating our own preconfigured Vagrant box some time?

**Comment by MMatten** [comment]
Regarding the failed test: my bad - this was left over from helping the user on the Google forum.

**Comment by MMatten** [comment]
Right, so `chef/centos-7.1` is working pretty well with your changes (apart from the vagrant port forwarding) - I've run all integration tests for MySQL, Postgres, Derby and HSQLDB.

There not room for both Oracle and DB2 on the base box. I've not done the disk/file system analysis yet. I'll do that this evening if I get some time.

May be there's also a way to add more disks and mount them in Vagrantfile.

**Comment by javornikolov** [comment]
> May be there's also a way to add more disks and mount them in Vagrantfile.

Yes, currently we have ability to customize RAM size. For disks it's a bit more complicated but can be done too:
http://unix.stackexchange.com/questions/176687/set-storage-size-on-creation-of-vm-virtualbox
http://jeqo.github.io/blog/devops/vagrant-quickstart/

BTW, Oracle Linux 7.1 might be another option (if there is a suitable vagrant box with it).

**Comment by MMatten** [comment]
Looking at the disk in the VB GUI it says

SATA Controller (type AHCI, port count 1)
-> box-disk1.vmdk (SATA port 0, type Normal (VMDK): virtual size 9.9GB, actual size 2.7GB, dynamically allocated storage)

So that suggests....I'm not sure if that means it can auto-grow somehow. I'll take a look at those links later.

The file system appears to be using all of the disk: -

```
vagrant@dbfitvm /]$  df -k .
filesystem              1K-blocks    Used Available Use% Mounted on
dev/mapper/centos-root   8775680 6929108   1846572  79% /

**Comment by javornikolov** [comment]
You're checking just the root file system, there might be others - what's the output of `df -h` (without the dot "." at the end).

`/dev/mapper/...` - suggests that LVM2 is being used. To check space in LVM groups and volumes:
``` bash
pvs
vgs
lvs
```

Might be handy to know the swap size: `swapon -s`

**Comment by MMatten** [comment]
Ah, yes. This is much more revealing.

```
[vagrant@dbfitvm dbfit]$ df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-root  8.4G  6.2G  2.2G  75% /
devtmpfs                 528M     0  528M   0% /dev
tmpfs                    534M  4.0K  534M   1% /dev/shm
tmpfs                    534M  7.0M  527M   2% /run
tmpfs                    534M     0  534M   0% /sys/fs/cgroup
/dev/sda1                497M   83M  414M  17% /boot
none                     507G  412G   95G  82% /vagrant
none                     507G  412G   95G  82% /var/dbfit
none                     507G  412G   95G  82% /tmp/vagrant-chef/fef29433d03cac37dc603db1ce2d9b9d/cookbooks
```

So we could possibly install Oracle/DB2/Informix outside of the 9.9GB drive of the box (on the host's shared 507GB drive) although perhaps there could be file system issues. It feels a bit strange too having Linux binaries accessible via Windows Explorer!

**Comment by MMatten** [comment]
The other commads show:

```
[vagrant@dbfitvm vagrant]$ sudo pvs
  PV         VG     Fmt  Attr PSize PFree
  /dev/sda2  centos lvm2 a--  9.41g 40.00m

vagrant@dbfitvm vagrant]$ sudo vgs
  VG     #PV #LV #SN Attr   VSize VFree
  centos   1   2   0 wz--n- 9.41g 40.00m

[vagrant@dbfitvm vagrant]$ sudo lvs
  LV   VG     Attr       LSize    Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  root centos -wi-ao----    8.38g
  swap centos -wi-ao---- 1016.00m
```

**Comment by javornikolov** [comment]
Database on such kind of shared drive is not a good idea I think (potential problems with the latency, locking, permissions).
One option is to add another disk and add it to the volume group: then new logical volumes may be created or existing ones extended. https://gist.github.com/christopher-hopper/9755310

**Comment by MMatten** [comment]
The shell provisioning solution here does look like it could be nice and simple. 

https://jeqo.github.io/blog/devops/vagrant-quickstart/

I'll see if I can get it working.

**Comment by MMatten** [comment]
I've pieced together some clues and created PR #421 for review.
